### ISSUE TITLE
jsx-boolean-value rule discussion

### ISSUE THREAD

**Issue by itzsaga** [teamairship/tslint-react-config-airship#4]
After today's B&B moving this here. Thoughts on this rule?

![screen shot 2019-01-14 at 09 52 59](https://user-images.githubusercontent.com/11750061/51133967-e522bd00-17fb-11e9-8d2d-4a48ec1a4ecc.png)

From [tslint-react](https://github.com/palantir/tslint-react):
- `jsx-boolean-value` (since v2.5.0)
  - When using a boolean attribute in JSX, you can set the attribute value to true or omit the value. This rule will enforce one or the other to keep consistency in your code.
  - Rule options: `["always", "never"]`
  - Default is set to `always`.

I know @Rehubbard and I want to get rid of it.

**Comment by Rehubbard** [comment]
Yeah, I am okay with no true value being set. I think that is pretty standard in all of our React code.
