### ISSUE TITLE
no-submodule-imports rule discussion

### ISSUE THREAD

**Issue by itzsaga** [teamairship/tslint-react-config-airship#5]
I ran into this creating a custom Input component.

![screen shot 2019-01-14 at 14 03 22](https://user-images.githubusercontent.com/11750061/51137837-2bc8e500-1805-11e9-89ac-6932a381f544.png)

I think this one requires a little more thought and research https://palantir.github.io/tslint/rules/no-submodule-imports/

Maybe leave in the shared config and keep this as a project level rule to override?

**Comment by amhinson** [comment]
Yea, I've seen that one a lot as well. I ended up disabling the rule. I do that all the time for Lodash functions.
