### ISSUE TITLE
jsx-no-lambda discussion

### ISSUE THREAD

**Issue by amhinson** [teamairship/tslint-react-config-airship#7]
This seems to be based on the assumption that arrow functions in render are a performance problem, but a lot of people smarter than me have found that it isn't really an issue. Are yall good with adding `"jsx-no-lambda": false`?

**Comment by itzsaga** [comment]
I'm good with it based on your:
> a lot of people smarter than me have found that it isn't really an issue

I trust you've done your due diligence.
