### ISSUE TITLE
member-ordering rule discussion

### ISSUE THREAD

**Issue by itzsaga** [teamairship/tslint-react-config-airship#8]
Following the TS cheatsheet I ran into this rule:

![screen shot 2019-01-17 at 14 49 39](https://user-images.githubusercontent.com/11750061/51347975-1eab3080-1a67-11e9-9087-1c0fe49c9af2.png)

[Rule: member-ordering](https://palantir.github.io/tslint/rules/member-ordering/)

Since it doesn't stop compilation I think it's okay to keep it in there. It'll probably only crop up in `Provider` components and enforcing it elsewhere will keep a more consistent code style across projects.

**Comment by Rehubbard** [comment]
I am okay with leaving this rule in there. I think the consistency we'll gain amongst our team is beneficial.

**Comment by amhinson** [comment]
I agree! Seems like 99% of the time, they should be at the top, except for that Provider scenario.
